env_settings:
  num_envs: 6
  seed: 42

engine_settings:
  width: 800
  height: 600
  quality_level: 3
  time_scale: 20
  target_frame_rate: -1
  no_graphics: false

behaviors:
  Human:
    trainer_type: ppo

    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 15e-5
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 4

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 64
        time_horizon: 16
        use_recurrent: false

    max_steps: 4.0e8
    summary_freq: 204800
    keep_checkpoints: 2
    checkpoint_interval: 2000000

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.95

# Add this section
environment_parameters:
  speed:
    curriculum:
      - name: Stand
        completion_criteria:
          measure: reward
          behavior: Human
          signal_smoothing: true
          min_lesson_length: 2000
          threshold: 3.6 # ~90% รก 4=0.25*240/15
        value: 0.0
      - name: Walk
        completion_criteria:
          measure: reward
          behavior: Human
          signal_smoothing: true
          min_lesson_length: 2000
          threshold: 3.6 # ~90%
        value: 0.25
      - name: Spread
        completion_criteria:
          measure: reward
          behavior: Human
          signal_smoothing: true
          min_lesson_length: 2000
          threshold: 3.6 #  ~90%
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 0.5
      - name: Jog
        completion_criteria:
          measure: reward
          behavior: Human
          signal_smoothing: true
          min_lesson_length: 2000
          threshold: 3.6 #  ~90%
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 0.7
      - name: Run
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0