default:
  trainer: ppo
  batch_size: 1024
  beta: 5.0e-3
  buffer_size: 10240
  epsilon: 0.2
  hidden_units: 512
  lambd: 0.95
  learning_rate: 3.0e-4
  learning_rate_schedule: linear
  max_steps: 1.0e7
  memory_size: 256
  normalize: true
  num_epoch: 4
  num_layers: 3
  time_horizon: 64
  sequence_length: 64
  summary_freq: 10000
  use_recurrent: true
  vis_encode_type: simple
  keep_checkpoints: 2
  checkpoint_interval: 2e6
  reward_signals:
      extrinsic:
          strength: 1.0
          gamma: 0.995

quick:
  trainer: ppo
  batch_size: 512
  beta: 5.0e-3
  buffer_size: 5120
  epsilon: 0.3
  hidden_units: 512
  lambd: 0.95
  learning_rate: 3.0e-4
  learning_rate_schedule: linear
  max_steps: 3.0e7
  memory_size: 256
  normalize: true
  num_epoch: 4
  num_layers: 3
  time_horizon: 64
  sequence_length: 64
  summary_freq: 10000
  use_recurrent: true
  vis_encode_type: simple
  keep_checkpoints: 2
  checkpoint_interval: 2e6
  reward_signals:
      extrinsic:
          strength: 1.0
          gamma: 0.995

slow:
  trainer: ppo
  batch_size: 2048
  beta: 5.0e-3
  buffer_size: 20480
  epsilon: 0.1
  hidden_units: 512
  lambd: 0.95
  learning_rate: 3.0e-4
  learning_rate_schedule: linear
  max_steps: 3.0e7
  memory_size: 256
  normalize: true
  num_epoch: 1
  num_layers: 3
  time_horizon: 100
  sequence_length: 64
  summary_freq: 10000
  use_recurrent: true
  vis_encode_type: simple
  keep_checkpoints: 2
  checkpoint_interval: 2e6
  reward_signals:
      extrinsic:
          strength: 1.0
          gamma: 0.995
